# Generated by Django 5.2 on 2025-04-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('locatie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_produs', models.CharField(max_length=50)),
                ('numar_inceput', models.IntegerField()),
                ('numar_final', models.IntegerField()),
                ('numar_curent', models.IntegerField(default=0)),
                ('gestiune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificat.gestiune')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_document', models.IntegerField(unique=True)),
                ('aviz_number', models.CharField(max_length=100)),
                ('data_aviz', models.DateField()),
                ('beneficiar', models.CharField(max_length=200)),
                ('date_complementare', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gestiune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificat.gestiune')),
            ],
        ),
    ]
