# Generated by Django 5.2 on 2025-04-09 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('utilizator', 'Utilizator'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipologieProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentrange',
            name='tip_produs',
        ),
        migrations.AddField(
            model_name='documentrange',
            name='tipologie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certificat.tipologieprodus'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestiune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificat.gestiune')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificat.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
