# Generated by Django 5.2 on 2025-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0002_role_tipologieprodus_remove_documentrange_tip_produs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrange',
            name='numar_curent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrange',
            name='numar_final',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrange',
            name='numar_inceput',
            field=models.CharField(max_length=50),
        ),
    ]
