# Generated by Django 5.2 on 2025-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0003_alter_documentrange_numar_curent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ok_administrare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ok_aviz',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ok_gestiuni',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ok_plaje',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ok_raportare',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ok_tipologii',
            field=models.BooleanField(default=False),
        ),
    ]
