# Generated by Django 5.2 on 2025-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0004_userprofile_ok_administrare_userprofile_ok_aviz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestiune',
            name='cod_inregistrare',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ok_administrare',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ok_plaje',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ok_tipologii',
            field=models.BooleanField(default=True),
        ),
    ]
