# Generated by Django 5.2 on 2025-04-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0005_gestiune_cod_inregistrare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecieMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(max_length=100, unique=True)),
                ('tipologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificat.tipologieprodus')),
            ],
        ),
    ]
