# Generated by Django 5.2 on 2025-04-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0006_speciemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('nr_ambalaje', models.DateField(blank=True, null=True)),
                ('doc_oficial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('etch_oficiale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('puritate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sem_straine', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('umiditate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('germinatie', models.CharField(blank=True, max_length=100, null=True)),
                ('masa_1000b', models.CharField(blank=True, max_length=100, null=True)),
                ('stare_sanitara', models.TextField(blank=True, null=True)),
                ('cold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('producator', models.CharField(blank=True, max_length=100, null=True)),
                ('tara_productie', models.CharField(blank=True, max_length=100, null=True)),
                ('samanta_tratata', models.CharField(blank=True, max_length=100, null=True)),
                ('garantie', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
