# Generated by Django 5.2 on 2025-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0008_alter_serieextradata_cold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ok_doc_generate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ok_raportare',
            field=models.BooleanField(default=False),
        ),
    ]
