# Generated by Django 5.2 on 2025-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0009_userprofile_ok_doc_generate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='aviz_number',
            field=models.CharField(max_length=100),
        ),
    ]
