# Generated by Django 5.2 on 2025-04-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0010_alter_generateddocument_aviz_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='document_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='partner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('salvat', 'Salvat'), ('finalizat', 'Finalizat')], default='salvat', max_length=10),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_docs/'),
        ),
    ]
