# Generated by Django 5.2 on 2025-04-14 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0011_generateddocument_document_series_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serieextradata',
            options={'verbose_name': 'Date Extra Serie', 'verbose_name_plural': 'Date Extra Serii'},
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('salvat', 'Salvat'), ('finalizat', 'Finalizat'), ('in procesare', 'In procesare')], default='salvat', max_length=20),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='cold',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='doc_oficial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='etch_oficiale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='germinatie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='masa_1000b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='nr_ambalaje',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='producator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='puritate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='samanta_tratata',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='sem_straine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='serie',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='stare_sanitara',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serieextradata',
            name='umiditate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Dată și Oră')),
                ('action_type', models.CharField(blank=True, max_length=100, verbose_name='Tip Acțiune')),
                ('details', models.TextField(verbose_name='Detalii Acțiune')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Înregistrare Jurnal Activitate',
                'verbose_name_plural': 'Jurnal Activitate',
                'ordering': ['-timestamp'],
            },
        ),
    ]
