# Generated by Django 5.2 on 2025-04-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0012_alter_serieextradata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text citatei')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
            ],
            options={
                'verbose_name': 'Citat Zilnic',
                'verbose_name_plural': 'Citate Zilnice',
            },
        ),
    ]
