# Generated by Django 5.2 on 2025-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0013_dailyquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titlu Manual')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriere')),
                ('file', models.FileField(upload_to='manuals/', verbose_name='Fișier Manual')),
                ('version', models.CharField(max_length=20, verbose_name='Versiune')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='Data Încărcare')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
            ],
            options={
                'verbose_name': 'Manual Utilizare',
                'verbose_name_plural': 'Manuale Utilizare',
                'ordering': ['-upload_date'],
            },
        ),
    ]
