# Generated by Django 5.2 on 2025-10-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0015_generateddocument_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vede_toate_documentele',
            field=models.BooleanField(default=False, help_text='Dacă este bifat, utilizatorul vede toate documentele din sistem. Altfel, vede doar documentele generate de el.'),
        ),
    ]
