# Generated by Django 5.2 on 2025-08-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0015_generateddocument_deleted_at_and_more'),
        ('certificat', '0015_generateddocument_regenerated_and_more'),
    ]

    operations = [
    ]
