# Generated by Django 5.2 on 2025-10-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0016_userprofile_vede_toate_documentele'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ok_administrare',
            field=models.BooleanField(default=True, help_text='Permite accesul la pagina de administrare'),
        ),
        migrations.AddField(
            model_name='role',
            name='ok_aviz',
            field=models.BooleanField(default=True, help_text='Permite generarea de avize/certificate'),
        ),
        migrations.AddField(
            model_name='role',
            name='ok_doc_generate',
            field=models.BooleanField(default=False, help_text='Permite vizualizarea documentelor generate'),
        ),
        migrations.AddField(
            model_name='role',
            name='ok_gestiuni',
            field=models.BooleanField(default=True, help_text='Permite gestionarea gestiunilor'),
        ),
        migrations.AddField(
            model_name='role',
            name='ok_plaje',
            field=models.BooleanField(default=True, help_text='Permite gestionarea plajelor de numere'),
        ),
        migrations.AddField(
            model_name='role',
            name='ok_raportare',
            field=models.BooleanField(default=False, help_text='Permite accesul la pagina de raportare'),
        ),
        migrations.AddField(
            model_name='role',
            name='ok_tipologii',
            field=models.BooleanField(default=True, help_text='Permite gestionarea tipologiilor'),
        ),
        migrations.AddField(
            model_name='role',
            name='vede_toate_documentele',
            field=models.BooleanField(default=False, help_text='Utilizatorul vede toate documentele sau doar pe ale lui'),
        ),
    ]
