# Generated by Django 5.2 on 2025-10-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0016_merge_20250821_1008'),
        ('certificat', '0017_role_ok_administrare_role_ok_aviz_and_more'),
    ]

    operations = [
    ]
