# Generated by Django 5.2 on 2026-02-13 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificat', '0018_merge_20251023_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Tip Acțiune'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Dată și Oră'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='aviz_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='document_series',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('salvat', 'Salvat'), ('finalizat', 'Finalizat'), ('in procesare', 'In procesare')], db_index=True, default='salvat', max_length=20),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['is_deleted', 'created_at'], name='idx_doc_active_date'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['generated_by', 'is_deleted'], name='idx_doc_user_active'),
        ),
    ]
